# Generated by Django 4.1.3 on 2022-11-10 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_cita_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Aplicacion.especialidad'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Aplicacion.paciente'),
        ),
    ]
