# Generated by Django 4.1.3 on 2022-11-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0004_tag_cita_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='tags',
        ),
    ]
