# Generated by Django 4.1.3 on 2022-11-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0005_remove_cita_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='tags',
            field=models.ManyToManyField(to='Aplicacion.tag'),
        ),
    ]
