# Generated by Django 4.1.3 on 2022-11-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0007_alter_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='nota',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
