# Generated by Django 4.1.3 on 2022-11-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0008_cita_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='nota',
        ),
        migrations.AddField(
            model_name='cita',
            name='medico',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
