# Generated by Django 4.1.3 on 2022-11-10 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0009_remove_cita_nota_cita_medico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='medico',
            new_name='nota',
        ),
    ]
