# Generated by Django 4.1.3 on 2022-11-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0010_rename_medico_cita_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Atendida', 'Atendida')], max_length=200, null=True),
        ),
    ]
