# Generated by Django 4.1.3 on 2022-11-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0011_alter_cita_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='nota',
            new_name='medico',
        ),
    ]
