# Generated by Django 4.1.3 on 2022-11-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0012_rename_nota_cita_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='categoria',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=200, null=True),
        ),
    ]
