# Generated by Django 4.1.3 on 2022-11-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0013_alter_especialidad_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('No Asistió', 'No Asistió'), ('Atendida', 'Atendida')], max_length=200, null=True),
        ),
    ]
