# Generated by Django 4.1.3 on 2022-11-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0014_alter_cita_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidad',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
